### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by realityking** [joscha/node-detective-postcss#13]
Hey @joscha. Could you tag a new (major) release? Would be great if precint could pick up the new version.

Thank you!

**Comment by joscha** [comment]
hey, can do, but I think precinct needs a PR to pick up a new version - it's not very modular right now. I know that @mrjoelkemp would love that to happen though: https://github.com/dependents/node-precinct/issues/17

**Comment by joscha** [comment]
`3.0.0` is out.

**Comment by realityking** [comment]
Thanks @joscha! No worries about precinct, I‘ll open a PR.
