### ISSUE TITLE
Is postcss-values-parser.d.ts needed?

### ISSUE THREAD

**Issue by XhmikosR** [joscha/node-detective-postcss#155]
@joscha I was wondering if https://github.com/dependents/node-detective-postcss/blob/master/src/postcss-values-parser.d.ts is still needed? AFAICT postcss-values-parser has TypeScript definitions: https://github.com/shellscape/postcss-values-parser/blob/master/lib/index.d.ts.

**Comment by joscha** [comment]
I vaguely remember I had to add this either before it was available or because there were compat issues. We should try to remove it 100%.
