### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by jackiewmacharia** [joscha/node-detective-postcss#180]
We are encountering this error with node v18 in CI via our [precinct v9.0.1](https://github.com/dependents/node-precinct) dependency `error detective-postcss@6.0.1: The engine "node" is incompatible with this module. Expected version "12.x || 14.x || 16.x". Got "18.2.0"`. This [commit](https://github.com/dependents/node-detective-postcss/commit/ad2befa8c2e07e31b0acbd8e7c9b6a9fd89f8268) would fix it but it hasn't been released yet. Any plans of having the next release out soon?

**Comment by joscha** [comment]
That's an oversight, we should have released that already. I'll look to cut one this weekend.

**Comment by joscha** [comment]
> Successfully published detective-postcss v6.1.0 to NPM
