### ISSUE TITLE
release v5.1.2 to loosen node version restriction

### ISSUE THREAD

**Issue by viceice** [joscha/node-detective-postcss#201]
Currently the version v5.1.1 don't allow node v18, so install fails on that node version.

So please release a bugfix with will allow any node version >= 16.0.0

It's already fixed on v5.x branch:

https://github.com/dependents/node-detective-postcss/blob/2a87325791d3d0bb2327669a902cf7009dc647e8/package.json#L13

**Comment by joscha** [comment]
Is there any chance you can upgrade to v6?

**Comment by viceice** [comment]
not directly, as this is a transitive dependency 🤷‍♂️

**Comment by joscha** [comment]
> not directly, as this is a transitive dependency 🤷‍♂️

are we talking about
https://github.com/pahen/madge/blob/c12ef70836855df7b9c34e5d93dfd34fdcae230d/package.json#L55 or something else?

**Comment by viceice** [comment]
yes

**Comment by joscha** [comment]
Sorry, I am not following, yet. So we can't upgrade it there, because...?
Reason I am asking is that I'd prefer consumers to get to 6.x rather than
staying on 5.x assuming compatibility with latest node versions.

**Comment by viceice** [comment]
i understand, but it seems madge isn't merging the update PR. maybe there's no maintainer. 😕

**Comment by viceice** [comment]
PR is open since 4 month 😕
- https://github.com/pahen/madge/pull/319

**Comment by joscha** [comment]
I just published 5.1.3, hope that helps!
