### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ndtrung1307** [joscha/node-detective-postcss#62]
I met this error when run test
![image](https://user-images.githubusercontent.com/50735949/77521031-a20ab200-6eb4-11ea-84e1-a317bc6ef22a.png)
pls help me to take a look

**Comment by joscha** [comment]
ah, this happens because the node module packages the tests by accident. Would you mind opening a PR? I think using the `"files"` key in the package.json should do it.
